package ui;

import da.DataAccessShoes;
import ds.Shoes;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import form.FormHome;
import java.awt.BorderLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ethan
 */
public class mainScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainScreen
     */
    
    private FormHome home;
    
    public mainScreen() {
        initComponents();
        initAppearance();
        this.setLocationRelativeTo(null);
        this.setSize(535, 420);
        addOrRemoveScreen.setLocationRelativeTo(null);
        addOrRemoveScreen.setSize(253, 280);
        clearSearchButton.setVisible(false);
        increaseOrDecreaseScreen.setSize(400, 300);
        increaseOrDecreaseScreen.setLocationRelativeTo(null);
        stockLabel.setText("");
        priceLabel.setText("");
    }
    
    public void initAppearance(){
        Object [] title = {"ID", "Name", "Price ($)", "Stock", "Size", "Gender"};
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <Shoes> shoeList = das.showShoes();
        Object [][] ObjShoes = new Object[shoeList.size()][title.length];
        for (int i = 0; i < shoeList.size(); i++){
            Shoes shoes = shoeList.get(i);
            ObjShoes[i][0] = shoes.getId();
            ObjShoes[i][1] = shoes.getName();
            ObjShoes[i][2] = shoes.getPrice();
            ObjShoes[i][3] = shoes.getStock();
            ObjShoes[i][4] = shoes.getSize();
            ObjShoes[i][5] = shoes.getGender();
        }
        DefaultTableModel dtm = new DefaultTableModel(ObjShoes, title);
        mainTable.setModel(dtm);
        jScrollPane1.setViewportView(mainTable);
        mainTable.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOrRemoveScreen = new javax.swing.JFrame();
        title2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        stockTF = new javax.swing.JTextField();
        sizeTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        increaseOrDecreaseScreen = new javax.swing.JFrame();
        nameDropdown = new javax.swing.JComboBox<>();
        sizeDropdown = new javax.swing.JComboBox<>();
        genderDropdown = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        minusStock = new javax.swing.JLabel();
        plusStock = new javax.swing.JLabel();
        plusPrice = new javax.swing.JLabel();
        minusPrice = new javax.swing.JLabel();
        test = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        addOrRemoveButton = new javax.swing.JButton();
        searchButton = new javax.swing.JLabel();
        clearSearchButton = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        addOrRemoveScreen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title2.setText("ADD / REMOVE");
        addOrRemoveScreen.getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        addOrRemoveScreen.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        jLabel1.setText("Name:");
        addOrRemoveScreen.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setText("Price:");
        addOrRemoveScreen.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Stock:");
        addOrRemoveScreen.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("Size:");
        addOrRemoveScreen.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Gender:");
        addOrRemoveScreen.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        addOrRemoveScreen.getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, -1));

        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        addOrRemoveScreen.getContentPane().add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 170, -1));

        stockTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTFActionPerformed(evt);
            }
        });
        addOrRemoveScreen.getContentPane().add(stockTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, -1));
        addOrRemoveScreen.getContentPane().add(sizeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, -1));
        addOrRemoveScreen.getContentPane().add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, -1));

        addButton.setBackground(new java.awt.Color(204, 255, 204));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addOrRemoveScreen.getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        removeButton.setBackground(new java.awt.Color(255, 204, 204));
        removeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        addOrRemoveScreen.getContentPane().add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("←");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        addOrRemoveScreen.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jLabel6.setText("jLabel6");

        jTextField2.setText("jTextField2");

        jLabel7.setText("jLabel7");

        jLabel9.setText("jLabel9");

        increaseOrDecreaseScreen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nameDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDropdownActionPerformed(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(nameDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, -1));

        sizeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sizeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeDropdownActionPerformed(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(sizeDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        genderDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderDropdownActionPerformed(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(genderDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, -1));
        increaseOrDecreaseScreen.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("MODIFICATION");
        increaseOrDecreaseScreen.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("←");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("STOCK");
        increaseOrDecreaseScreen.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("PRICE");
        increaseOrDecreaseScreen.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        stockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        increaseOrDecreaseScreen.getContentPane().add(stockLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 100, 20));

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        increaseOrDecreaseScreen.getContentPane().add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 90, 20));

        minusStock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minusStock.setText("-");
        minusStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusStockMouseClicked(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(minusStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 40));

        plusStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusStock.setText("+");
        plusStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusStockMouseClicked(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(plusStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        plusPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusPrice.setText("+");
        plusPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusPriceMouseClicked(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(plusPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        minusPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minusPrice.setText("-");
        minusPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusPriceMouseClicked(evt);
            }
        });
        increaseOrDecreaseScreen.getContentPane().add(minusPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 40));

        test.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        test.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 300));

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setText("Sneaker Store Stock Manager");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        addOrRemoveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addOrRemoveButton.setText("ADD/REMOVE");
        addOrRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrRemoveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addOrRemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        searchButton.setText("🔍");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 20));

        clearSearchButton.setText("X");
        clearSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearSearchButtonMouseClicked(evt);
            }
        });
        getContentPane().add(clearSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 10, 20));

        searchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTFKeyReleased(evt);
            }
        });
        getContentPane().add(searchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("INC / DEC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOrRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrRemoveButtonActionPerformed
        addOrRemoveScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addOrRemoveButtonActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (nameTF.getText().isEmpty()||sizeTF.getText().isEmpty()||genderTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the required fields");
        }else{
            int input = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION);
            System.out.println(input);
            if (input == 0){
                DataAccessShoes das = new DataAccessShoes();
                String name = nameTF.getText();
                int size = Integer.valueOf(sizeTF.getText());
                String gender = genderTF.getText();
                String condition = das.removeShoes(name, size, gender);
                if (condition.equals("true")){
                    JOptionPane.showMessageDialog(null, "Successfully removed");
                    nameTF.setText("");
                    priceTF.setText("");
                    stockTF.setText("");
                    sizeTF.setText("");
                    genderTF.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Failed to remove");
                }
            }else{
                addOrRemoveScreen.setVisible(true);
            }
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (nameTF.getText().isEmpty()||priceTF.getText().isEmpty()||stockTF.getText().isEmpty()||sizeTF.getText().isEmpty()||genderTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }else{
            int input = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION);
            System.out.println(input);
            if (input == 0){
                DataAccessShoes das = new DataAccessShoes();
                String name = nameTF.getText();
                double price = Double.valueOf(priceTF.getText());
                int stock = Integer.valueOf(stockTF.getText());
                int size = Integer.valueOf(sizeTF.getText());
                String gender = genderTF.getText();
                String condition = das.newShoes(name, price, stock, size, gender);
                if (condition.equals("true")){
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    nameTF.setText("");
                    priceTF.setText("");
                    stockTF.setText("");
                    sizeTF.setText("");
                    genderTF.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Failed to add");
                }
            }else{
                addOrRemoveScreen.setVisible(true);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        addOrRemoveScreen.setVisible(false);
        this.setVisible(true);
        initAppearance();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        
    }//GEN-LAST:event_searchButtonMouseClicked

    private void clearSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearSearchButtonMouseClicked
        searchTF.setText("");
        clearSearchButton.setVisible(false);
        initAppearance();
    }//GEN-LAST:event_clearSearchButtonMouseClicked

    private void stockTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTFActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void nameDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDropdownActionPerformed
        
    }//GEN-LAST:event_nameDropdownActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        increaseOrDecreaseScreen.setVisible(true);
        this.setVisible(false);
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <String> name = das.showNameDropdown();
        String[] names = new String[name.size()];
        for (int i = 0; i < name.size(); i++){
            names[i] = name.get(i);
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(names);
        nameDropdown.setModel(model);
        
        ArrayList <String> size = das.showSizeDropdown();
        String[] sizes = new String[size.size()];
        for (int i = 0; i < name.size(); i++){
            sizes[i] = size.get(i);
        }
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>(sizes);
        sizeDropdown.setModel(model2);
        
        String[] gender = {"men", "women"};
        DefaultComboBoxModel<String> model3 = new DefaultComboBoxModel<>(gender);
        genderDropdown.setModel(model3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void genderDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderDropdownActionPerformed

    private void sizeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeDropdownActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        increaseOrDecreaseScreen.setVisible(false);
        this.setVisible(true);
        initAppearance();
        stockLabel.setText("");
        priceLabel.setText("");
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <String> names = das.showNameDropdown();
        int nameIndex = nameDropdown.getSelectedIndex();
        String name = names.get(nameIndex);
        ArrayList <String> sizes = das.showSizeDropdown();
        int sizeIndex = sizeDropdown.getSelectedIndex();
        int size = Integer.valueOf(sizes.get(sizeIndex));
        int genderIndex = genderDropdown.getSelectedIndex();
        String gender;
        if (genderIndex == 0){
            gender = "men";
        }else{
            gender = "women";
        }
        
        String confirm = das.checkID(name, size, gender);
        if(confirm.equals("true")){
            String[] info = das.getStockAndPrice(name, size, gender);
            double price = Double.valueOf(info[0]);
            int stock = Integer.valueOf(info[1]);
            priceLabel.setText(info[0]);
            stockLabel.setText(info[1]);
        }else{
            priceLabel.setText("No product");
            stockLabel.setText("No product");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void plusStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusStockMouseClicked
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <String> names = das.showNameDropdown();
        int nameIndex = nameDropdown.getSelectedIndex();
        String name = names.get(nameIndex);
        ArrayList <String> sizes = das.showSizeDropdown();
        int sizeIndex = sizeDropdown.getSelectedIndex();
        int size = Integer.valueOf(sizes.get(sizeIndex));
        int genderIndex = genderDropdown.getSelectedIndex();
        String gender;
        if (genderIndex == 0){
            gender = "men";
        }else{
            gender = "women";
        }
        int stock = Integer.valueOf(stockLabel.getText())+1;
        double price = Double.valueOf(priceLabel.getText());
        String confirm = das.changeShoes(price, stock, name, size, gender);
        if (confirm.equals("true")){
            stockLabel.setText(String.valueOf(stock));
        }else{
            increaseOrDecreaseScreen.setVisible(true);
        }
    }//GEN-LAST:event_plusStockMouseClicked

    private void searchTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTFKeyReleased
        clearSearchButton.setVisible(true);
        String searchQuery = "%"+searchTF.getText()+"%";
        Object [] title = {"ID", "Name", "Price ($)", "Stock", "Size", "Gender"};
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <Shoes> shoeList = das.showSpecific(searchQuery);
        Object [][] ObjShoes = new Object[shoeList.size()][title.length];
        for (int i = 0; i < shoeList.size(); i++){
            Shoes shoes = shoeList.get(i);
            ObjShoes[i][0] = shoes.getId();
            ObjShoes[i][1] = shoes.getName();
            ObjShoes[i][2] = shoes.getPrice();
            ObjShoes[i][3] = shoes.getStock();
            ObjShoes[i][4] = shoes.getSize();
            ObjShoes[i][5] = shoes.getGender();
        }
        DefaultTableModel dtm = new DefaultTableModel(ObjShoes, title);
        mainTable.setModel(dtm);
        jScrollPane1.setViewportView(mainTable);
        mainTable.setEnabled(false);
    }//GEN-LAST:event_searchTFKeyReleased

    private void minusStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusStockMouseClicked
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <String> names = das.showNameDropdown();
        int nameIndex = nameDropdown.getSelectedIndex();
        String name = names.get(nameIndex);
        ArrayList <String> sizes = das.showSizeDropdown();
        int sizeIndex = sizeDropdown.getSelectedIndex();
        int size = Integer.valueOf(sizes.get(sizeIndex));
        int genderIndex = genderDropdown.getSelectedIndex();
        String gender;
        if (genderIndex == 0){
            gender = "men";
        }else{
            gender = "women";
        }
        int stock = Integer.valueOf(stockLabel.getText())-1;
        double price = Double.valueOf(priceLabel.getText());
        String confirm = das.changeShoes(price, stock, name, size, gender);
        if (confirm.equals("true")){
            stockLabel.setText(String.valueOf(stock));
        }else{
            increaseOrDecreaseScreen.setVisible(true);
        }
    }//GEN-LAST:event_minusStockMouseClicked

    private void plusPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusPriceMouseClicked
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <String> names = das.showNameDropdown();
        int nameIndex = nameDropdown.getSelectedIndex();
        String name = names.get(nameIndex);
        ArrayList <String> sizes = das.showSizeDropdown();
        int sizeIndex = sizeDropdown.getSelectedIndex();
        int size = Integer.valueOf(sizes.get(sizeIndex));
        int genderIndex = genderDropdown.getSelectedIndex();
        String gender;
        if (genderIndex == 0){
            gender = "men";
        }else{
            gender = "women";
        }
        int stock = Integer.valueOf(stockLabel.getText());
        double price = Double.valueOf(priceLabel.getText())+1;
        String confirm = das.changeShoes(price, stock, name, size, gender);
        if (confirm.equals("true")){
            priceLabel.setText(String.valueOf(price));
        }else{
            increaseOrDecreaseScreen.setVisible(true);
        }
    }//GEN-LAST:event_plusPriceMouseClicked

    private void minusPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusPriceMouseClicked
        DataAccessShoes das = new DataAccessShoes();
        ArrayList <String> names = das.showNameDropdown();
        int nameIndex = nameDropdown.getSelectedIndex();
        String name = names.get(nameIndex);
        ArrayList <String> sizes = das.showSizeDropdown();
        int sizeIndex = sizeDropdown.getSelectedIndex();
        int size = Integer.valueOf(sizes.get(sizeIndex));
        int genderIndex = genderDropdown.getSelectedIndex();
        String gender;
        if (genderIndex == 0){
            gender = "men";
        }else{
            gender = "women";
        }
        int stock = Integer.valueOf(stockLabel.getText());
        double price = Double.valueOf(priceLabel.getText())-1;
        String confirm = das.changeShoes(price, stock, name, size, gender);
        if (confirm.equals("true")){
            priceLabel.setText(String.valueOf(price));
        }else{
            increaseOrDecreaseScreen.setVisible(true);
        }
    }//GEN-LAST:event_minusPriceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addOrRemoveButton;
    private javax.swing.JFrame addOrRemoveScreen;
    private javax.swing.JLabel clearSearchButton;
    private javax.swing.JComboBox<String> genderDropdown;
    private javax.swing.JTextField genderTF;
    private javax.swing.JFrame increaseOrDecreaseScreen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable mainTable;
    private javax.swing.JLabel minusPrice;
    private javax.swing.JLabel minusStock;
    private javax.swing.JComboBox<String> nameDropdown;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel plusPrice;
    private javax.swing.JLabel plusStock;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel searchButton;
    private javax.swing.JTextField searchTF;
    private javax.swing.JComboBox<String> sizeDropdown;
    private javax.swing.JTextField sizeTF;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JTextField stockTF;
    private javax.swing.JFrame test;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
